### ISSUE TITLE
File permissions (optional)

### ISSUE THREAD

**Issue by chrisave** [pH7Software/pH7-Documentation#1]
Please erase this issue.

**Comment by pH-7** [comment]
Please be more specific. Thank you

**Comment by chrisave** [comment]
Hello,

I hope you are doing well!

I had written a long post because I had doubts and needed confirmations concerning the specific folder/file permissions but later decided to remove it.

(I meant) Please remove completely this entire topic (this one that I created).

Thank you in advance.

Happy New Year 2019!

**Comment by pH-7** [comment]
Hi @chrisave 

I'm doing great, thanks! I hope you are doing great too 🤞

Ok, now it makes more sense! Thank you for these details :) I couldn't see the post you mention. You have probably removed it.

Happy New Year to you too Chris! All the best! 🍀
